// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: wal/entry.proto

package wal

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WALEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lsn           uint64                 `protobuf:"varint,1,opt,name=lsn,proto3" json:"lsn,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Crc           uint32                 `protobuf:"varint,3,opt,name=crc,proto3" json:"crc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WALEntry) Reset() {
	*x = WALEntry{}
	mi := &file_wal_entry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WALEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WALEntry) ProtoMessage() {}

func (x *WALEntry) ProtoReflect() protoreflect.Message {
	mi := &file_wal_entry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WALEntry.ProtoReflect.Descriptor instead.
func (*WALEntry) Descriptor() ([]byte, []int) {
	return file_wal_entry_proto_rawDescGZIP(), []int{0}
}

func (x *WALEntry) GetLsn() uint64 {
	if x != nil {
		return x.Lsn
	}
	return 0
}

func (x *WALEntry) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *WALEntry) GetCrc() uint32 {
	if x != nil {
		return x.Crc
	}
	return 0
}

var File_wal_entry_proto protoreflect.FileDescriptor

const file_wal_entry_proto_rawDesc = "" +
	"\n" +
	"\x0fwal/entry.proto\x12\x03wal\"H\n" +
	"\bWALEntry\x12\x10\n" +
	"\x03lsn\x18\x01 \x01(\x04R\x03lsn\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x10\n" +
	"\x03crc\x18\x03 \x01(\rR\x03crcB\aZ\x05./walb\x06proto3"

var (
	file_wal_entry_proto_rawDescOnce sync.Once
	file_wal_entry_proto_rawDescData []byte
)

func file_wal_entry_proto_rawDescGZIP() []byte {
	file_wal_entry_proto_rawDescOnce.Do(func() {
		file_wal_entry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wal_entry_proto_rawDesc), len(file_wal_entry_proto_rawDesc)))
	})
	return file_wal_entry_proto_rawDescData
}

var file_wal_entry_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_wal_entry_proto_goTypes = []any{
	(*WALEntry)(nil), // 0: wal.WALEntry
}
var file_wal_entry_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_wal_entry_proto_init() }
func file_wal_entry_proto_init() {
	if File_wal_entry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wal_entry_proto_rawDesc), len(file_wal_entry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wal_entry_proto_goTypes,
		DependencyIndexes: file_wal_entry_proto_depIdxs,
		MessageInfos:      file_wal_entry_proto_msgTypes,
	}.Build()
	File_wal_entry_proto = out.File
	file_wal_entry_proto_goTypes = nil
	file_wal_entry_proto_depIdxs = nil
}
